default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: voteazaparlament
  password: <%= ENV.fetch("PG_PASSWORD") { 'testpgpass' } %>

development:
  <<: *default
  database: voteazaparlament_development

test:
  <<: *default
  database: voteazaparlament_test

production:
  primary:
    <<: *default
    database: voteazaparlament_production
  cable:
    adapter: postgresql
    url: <%= ENV['DATABASE_URL'] %>
  queue:
    adapter: postgresql
    url: <%= ENV['DATABASE_URL'] %>
  cache:
    adapter: postgresql
    url: <%= ENV['DATABASE_URL'] %>